dashboard/urls.py
from django.urls import path
from . import views

app_name = "dashboard"

urlpatterns = [
    path('', views.dashboard_view, name='dashboard_home'),
    path('mood-calendar/', views.mood_calendar_view, name='mood_calendar'),
    path('mood-history/', views.mood_history_view, name='mood_history'),
    path('edit-mood/<int:pk>/', views.edit_mood_view, name='edit_mood'),
    path('delete-mood/<int:pk>/', views.delete_mood_view, name='delete_mood'),
    path('send-reminders/', views.trigger_send_reminders, name='trigger_send_reminders'),
    path('settings/', views.settings_view, name='settings'),
]

mood/urls.py
from django.urls import path
from . import views

app_name = "mood"

urlpatterns = [
    path("entry/", views.mood_entry_view, name="mood_entry"),
]

moodtracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect, render

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('dashboard/', include('dashboard.urls')),  # Dashboard URLs
    path('mood/', include('mood.urls')),  # Mood tracking URLs
    path('users/', include('users.urls')),
    path('', lambda request: render(request, 'home.html'), name='home'),
]

users/urls.py
from django.urls import path
from .views import logout_confirm_view, ProfileUpdateView, CustomPasswordChangeView

app_name = "users"

urlpatterns = [
    path("logout/", logout_confirm_view, name="logout_confirm"),
    path("edit-profile/", ProfileUpdateView.as_view(), name="edit_profile"),
    path("change-password/", CustomPasswordChangeView.as_view(), name="change_password"),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" class="{% if user.preferences.dark_mode_enabled %}dark-theme{% endif %}">


<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Mood Tracker is a web application to log your daily moods, reflect on emotional patterns, and gain insights to improve your mental well-being.">
    <title>{% block title %}Mood Tracker{% endblock %}</title>
    <!-- Bootstrap 5 CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom Styles -->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <!-- Favicon -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'favicon/site.webmanifest' %}">
    <!-- Fontawesome -->
    <script src="https://kit.fontawesome.com/7ac6e7be0c.js" crossorigin="anonymous"></script>
    <script src="https://d3js.org/d3.v6.min.js"></script>
    <script src="{% static 'js/mood_history.js' %}"></script>
    <script src="{% static 'js/mood_calendar.js' %}"></script>
</head>


<body class="d-flex flex-column min-vh-100 {% if request.user.is_authenticated and request.user.profile.dark_theme %}dark-theme{% endif %}">
    <header>
        <nav class="navbar navbar-expand-lg {% if request.session.dark_theme %}navbar-dark bg-dark{% else %}navbar-light bg-light{% endif %}">
            <div class="container-fluid">
                <a class="navbar-brand" href="/">Mood Tracker</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ms-auto">
                        {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'dashboard:dashboard_home' %}">Dashboard</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'dashboard:mood_history' %}">History</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'dashboard:settings' %}">Settings</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'users:logout_confirm' %}">Logout</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="/">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'account_login' %}">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'account_signup' %}">Sign Up</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>        
    </header>
    
    <main class="container flex-grow-1 my-4">
        {% if messages %}
        <div class="container mt-3">
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
        </div>
        {% endif %}
        {% block content %}
        {% endblock %}
    </main>
    <footer class="text-center py-3 {% if request.session.dark_theme %}bg-dark text-light{% else %}bg-light text-dark{% endif %}">
        <a href="https://github.com/arthur-vilela/PP4-mood-tracker"><i class="fa-brands fa-github"></i></a>
        <p class="mb-0">&copy; 2025 Mood Tracker</p>
    </footer>
    <!-- Bootstrap Bundle JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>

templates/home.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Home - Mood Tracker
{% endblock %}

{% block content %}

    <div class="container py-5">
        <div class="row gx-5 align-items-center">
            <div class="col-xxl-5">
                <!-- Header text content-->
                <div class="text-center text-xxl-start">
                    <div class="badge bg-gradient-primary-to-secondary text-white mb-4">
                        <div class="text-uppercase">Design &middot; Development &middot; Marketing</div>
                    </div>
                    <div class="fs-3 fw-light text-muted">Welcome to</div>
                    <h1 class="display-3 fw-bolder mb-5"><span class="text-gradient d-inline">Mood Tracker</span></h1>
                    <div class="d-grid gap-3 d-sm-flex justify-content-sm-center justify-content-xxl-start mb-3">
                        {% if user.is_authenticated %}
                        <a href="{% url 'mood:mood_entry' %}"
                            class="btn btn-primary btn-lg px-5 py-3 me-sm-3 fs-6 fw-bolder">Add Mood Entry</a>
                        {% else %}
                        <a href="{% url 'account_login' %}" class="btn btn-primary btn-lg px-5 py-3 me-sm-3 fs-6 fw-bolder">Login</a>
                        <a href="{% url 'account_signup' %}" class="btn btn-outline-dark btn-lg px-5 py-3 fs-6 fw-bolder">Sign Up</a>
                        {% endif %}
                    </div>
                    <p><em>Track your daily moods and discover patterns in your emotions</em></p>
                </div>
            </div>
            <div class="col-xxl-7">
                <div class="d-flex justify-content-center mt-5 mt-xxl-0">
                    <div class="profile bg-gradient-primary-to-secondary">
                        <img class="profile-img" src="{% static 'images/illustration-home-page.png' %}" alt="Illustration of woman on laptop and a calendar" />
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}